services:
  portfolio_nycolaide_v2:
    container_name: portfolio_nycolaide_v2
    build:
      context: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio_nycolaide_v2.rule=Host(`v2.nycolaide.dev`)"
      - "traefik.http.routers.portfolio_nycolaide_v2.tls=true"
      - "traefik.http.routers.portfolio_nycolaide_v2.tls.certresolver=letsencrypt"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
