name: Deploy to VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ou la version que tu utilises

      - name: Install dependencies
        run: npm install

      - name: Build Svelte project
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 55555
          script: |
            cd /apps/portfolio-lgi/alpha
            git pull origin develop
            npm install
            docker compose build
            docker compose up -d
